import "server-only";
import type { Prisma } from "@prisma/client";
import { decryptField, maskValue } from "@/lib/crypto";
import { dateToYmd } from "@/lib/ops-helpers";
import type {
  LeaveRequestRecord,
  WarningRecord,
  FineRecord,
  CancellationRecord,
  UniformIssueRecord,
} from "@/types/manpower";

// ---------------------------------------------------------------------------
// Leave requests
// ---------------------------------------------------------------------------

export const LEAVE_INCLUDE = {
  employee: { select: { fullName: true, employeeCode: true } },
} satisfies Prisma.LeaveRequestInclude;

export type LeaveWithEmployee = Prisma.LeaveRequestGetPayload<{
  include: typeof LEAVE_INCLUDE;
}>;

export function toLeaveRecord(row: LeaveWithEmployee): LeaveRequestRecord {
  return {
    id: row.id,
    employeeId: row.employeeId,
    employeeName: row.employee.fullName,
    employeeCode: row.employee.employeeCode,
    leaveType: row.leaveType as LeaveRequestRecord["leaveType"],
    otherType: row.otherType,
    startDate: dateToYmd(row.startDate),
    endDate: dateToYmd(row.endDate),
    totalDays: row.totalDays,
    reason: row.reason,
    status: row.status as LeaveRequestRecord["status"],
    createdByName: row.createdByName,
    reviewedByName: row.reviewedByName,
    reviewedAt: row.reviewedAt ? row.reviewedAt.toISOString() : null,
    createdAt: row.createdAt.toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Warnings
// ---------------------------------------------------------------------------

export const WARNING_INCLUDE = {
  employee: { select: { fullName: true, employeeCode: true } },
} satisfies Prisma.WarningInclude;

export type WarningWithEmployee = Prisma.WarningGetPayload<{
  include: typeof WARNING_INCLUDE;
}>;

/** Parse the JSON-string absentDates column into a clean string[]. */
export function parseAbsentDates(json: string | null): string[] {
  if (!json) return [];
  try {
    const parsed: unknown = JSON.parse(json);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter((x): x is string => typeof x === "string");
  } catch {
    return [];
  }
}

export function toWarningRecord(row: WarningWithEmployee): WarningRecord {
  return {
    id: row.id,
    employeeId: row.employeeId,
    employeeName: row.employee.fullName,
    employeeCode: row.employee.employeeCode,
    reason: row.reason,
    isAutoGenerated: row.isAutoGenerated,
    absentDates: parseAbsentDates(row.absentDates),
    ratingPenalty: row.ratingPenalty,
    createdByName: row.createdByName,
    createdAt: row.createdAt.toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Fines
// ---------------------------------------------------------------------------

export const FINE_INCLUDE = {
  employee: { select: { fullName: true, employeeCode: true } },
} satisfies Prisma.FineInclude;

export type FineWithEmployee = Prisma.FineGetPayload<{
  include: typeof FINE_INCLUDE;
}>;

export function toFineRecord(row: FineWithEmployee): FineRecord {
  return {
    id: row.id,
    employeeId: row.employeeId,
    employeeName: row.employee.fullName,
    employeeCode: row.employee.employeeCode,
    reason: row.reason,
    amount: row.amount,
    currency: row.currency,
    ratingPenalty: row.ratingPenalty,
    createdByName: row.createdByName,
    createdAt: row.createdAt.toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Cancellation requests
// ---------------------------------------------------------------------------

export const CANCELLATION_INCLUDE = {
  employee: {
    select: {
      fullName: true,
      employeeCode: true,
      currentSite: { select: { name: true } },
    },
  },
} satisfies Prisma.CancellationRequestInclude;

export type CancellationWithEmployee = Prisma.CancellationRequestGetPayload<{
  include: typeof CANCELLATION_INCLUDE;
}>;

export function toCancellationRecord(row: CancellationWithEmployee): CancellationRecord {
  return {
    id: row.id,
    employeeId: row.employeeId,
    employeeName: row.employee.fullName,
    employeeCode: row.employee.employeeCode,
    employeeSiteName: row.employee.currentSite?.name ?? null,
    reason: row.reason,
    status: row.status as CancellationRecord["status"],
    requestedByName: row.requestedByName,
    reviewedByName: row.reviewedByName,
    reviewedAt: row.reviewedAt ? row.reviewedAt.toISOString() : null,
    createdAt: row.createdAt.toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Uniform issues
// ---------------------------------------------------------------------------

export const UNIFORM_ISSUE_INCLUDE = {
  employee: { select: { fullName: true, employeeCode: true } },
  site: { select: { name: true } },
  items: { include: { item: true } },
} satisfies Prisma.UniformIssueInclude;

export type UniformIssueWithRelations = Prisma.UniformIssueGetPayload<{
  include: typeof UNIFORM_ISSUE_INCLUDE;
}>;

/**
 * Serialize a uniform issue. `maskDocument` controls whether the decrypted
 * document number is masked (list views) or returned in full (creator views).
 */
export function toUniformIssueRecord(
  row: UniformIssueWithRelations,
  opts: { maskDocument?: boolean } = {}
): UniformIssueRecord {
  const documentNumber = decryptField(row.documentNumber);
  return {
    id: row.id,
    uniformCode: row.uniformCode,
    tokenNumber: row.tokenNumber,
    employeeId: row.employeeId,
    employeeName: row.employee.fullName,
    employeeCode: row.employee.employeeCode,
    documentType: row.documentType,
    documentNumber: opts.maskDocument
      ? maskValue(documentNumber) ?? ""
      : documentNumber ?? "",
    siteId: row.siteId,
    siteName: row.site?.name ?? null,
    teamLeaderName: row.teamLeaderName,
    isRenewal: row.isRenewal,
    previousIssueId: row.previousIssueId,
    issuedAt: row.issuedAt.toISOString(),
    renewalDate: dateToYmd(row.renewalDate),
    createdByName: row.createdByName,
    items: row.items
      .map((i) => ({ itemId: i.itemId, name: i.item.name, quantity: i.quantity }))
      .sort((a, b) => a.name.localeCompare(b.name)),
  };
}
