import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { ok, requirePermission } from "@/lib/api-helpers";
import {
  addDays,
  dateToYmd,
  getSettings,
  reviewAudience,
  round2,
  routeGuard,
  todayUtc,
  ymdToDate,
} from "@/lib/ops-helpers";
import { parseAbsentDates } from "@/lib/ops-serializers";

export const dynamic = "force-dynamic";

// ---------------------------------------------------------------------------
// POST /api/warnings/auto-check
// Scan the last 60 days of attendance for every active employee and create
// auto-generated warnings for runs of >= threshold consecutive absent days
// that are not already covered by an existing warning.
// ---------------------------------------------------------------------------

/** Split a sorted list of YYYY-MM-DD dates into maximal consecutive runs. */
function consecutiveRuns(dates: string[]): string[][] {
  const runs: string[][] = [];
  let current: string[] = [];
  let previous: string | null = null;
  for (const date of dates) {
    const expectedNext =
      previous !== null ? dateToYmd(addDays(ymdToDate(previous) as Date, 1)) : null;
    if (previous !== null && date === expectedNext) {
      current.push(date);
    } else {
      if (current.length > 0) runs.push(current);
      current = [date];
    }
    previous = date;
  }
  if (current.length > 0) runs.push(current);
  return runs;
}

export async function POST(req: NextRequest) {
  return routeGuard(async () => {
    const auth = await requirePermission(req, "warnings");
    if (auth.error) return auth.error;

    const settings = await getSettings();
    const threshold = settings.warningAbsenceThreshold;
    const penalty = settings.warningRatingPenalty;

    const today = todayUtc();
    const windowStart = addDays(today, -59); // 60-day window including today

    const employees = await db.employee.findMany({
      where: { status: "active" },
      select: { id: true, employeeCode: true, fullName: true, rating: true },
      orderBy: { employeeCode: "asc" },
    });

    const absentRows = await db.attendance.findMany({
      where: {
        status: "absent",
        attendanceDate: { gte: windowStart, lte: today },
        employeeId: { in: employees.map((e) => e.id) },
      },
      select: { employeeId: true, attendanceDate: true },
      orderBy: { attendanceDate: "asc" },
    });

    const absentByEmployee = new Map<string, string[]>();
    for (const row of absentRows) {
      const list = absentByEmployee.get(row.employeeId) ?? [];
      list.push(dateToYmd(row.attendanceDate));
      absentByEmployee.set(row.employeeId, list);
    }

    // Existing warnings' absent dates (per employee) — used to skip duplicates.
    const existingWarnings = await db.warning.findMany({
      where: { employeeId: { in: employees.map((e) => e.id) } },
      select: { employeeId: true, absentDates: true },
    });
    const coveredByEmployee = new Map<string, Set<string>>();
    for (const warning of existingWarnings) {
      const covered = coveredByEmployee.get(warning.employeeId) ?? new Set<string>();
      for (const date of parseAbsentDates(warning.absentDates)) covered.add(date);
      coveredByEmployee.set(warning.employeeId, covered);
    }

    const recipients = await reviewAudience("warnings", auth.user.id);
    let created = 0;
    const flaggedEmployees: string[] = [];

    for (const employee of employees) {
      const absentDates = absentByEmployee.get(employee.id);
      if (!absentDates || absentDates.length < threshold) continue;

      const covered = coveredByEmployee.get(employee.id) ?? new Set<string>();
      const candidateRuns = consecutiveRuns(absentDates)
        .filter((run) => run.length >= threshold)
        // A run already (even partially) covered by an existing warning is skipped,
        // so re-running the check never duplicates warnings.
        .filter((run) => !run.some((date) => covered.has(date)));
      if (candidateRuns.length === 0) continue;

      const newRating = Math.max(0, round2(employee.rating - candidateRuns.length * penalty));

      await db.$transaction(async (tx) => {
        for (const run of candidateRuns) {
          const warning = await tx.warning.create({
            data: {
              employeeId: employee.id,
              reason: `${run.length} consecutive unexplained absences`,
              isAutoGenerated: true,
              absentDates: JSON.stringify(run),
              ratingPenalty: penalty,
              createdByName: auth.user.fullName,
            },
          });
          if (recipients.length > 0) {
            await tx.notification.createMany({
              data: recipients.map((recipientId) => ({
                recipientId,
                type: "warning",
                title: "Warning auto-generated",
                message: `Auto-check flagged ${employee.fullName} (${employee.employeeCode}): ${run.length} consecutive unexplained absences.`,
                referenceType: "warning",
                referenceId: warning.id,
              })),
            });
          }
          await tx.auditLog.create({
            data: {
              actorId: auth.user.id,
              actorName: auth.user.fullName,
              action: "warning.auto_create",
              entity: "warning",
              entityId: warning.id,
              before: null,
              after: JSON.stringify({
                employeeId: employee.id,
                employeeCode: employee.employeeCode,
                reason: `${run.length} consecutive unexplained absences`,
                dates: run,
                newRating,
              }),
            },
          });
        }
        await tx.employee.update({
          where: { id: employee.id },
          data: { rating: newRating },
        });
      });

      created += candidateRuns.length;
      flaggedEmployees.push(employee.employeeCode);
    }

    return ok({ created, employees: flaggedEmployees });
  });
}
