import { NextRequest } from "next/server";
import { z } from "zod";
import type { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { ok, fail, requirePermission } from "@/lib/api-helpers";
import {
  getSettings,
  paginationOf,
  parseWith,
  reviewAudience,
  round2,
  routeGuard,
  zYmd,
} from "@/lib/ops-helpers";
import { WARNING_INCLUDE, toWarningRecord } from "@/lib/ops-serializers";

export const dynamic = "force-dynamic";

// ---------------------------------------------------------------------------
// GET /api/warnings?query&employeeId&page&pageSize (default pageSize 20)
// ---------------------------------------------------------------------------

export async function GET(req: NextRequest) {
  return routeGuard(async () => {
    const auth = await requirePermission(req, "warnings");
    if (auth.error) return auth.error;

    const url = new URL(req.url);
    const query = url.searchParams.get("query")?.trim() ?? "";
    const employeeId = url.searchParams.get("employeeId")?.trim() ?? "";
    const { page, pageSize, skip, take } = paginationOf(url, 20);

    const where: Prisma.WarningWhereInput = {};
    if (employeeId) where.employeeId = employeeId;
    if (query) {
      where.OR = [
        { employee: { fullName: { contains: query, mode: "insensitive" } } },
        { employee: { employeeCode: { contains: query, mode: "insensitive" } } },
        { reason: { contains: query, mode: "insensitive" } },
      ];
    }

    const [total, rows] = await Promise.all([
      db.warning.count({ where }),
      db.warning.findMany({
        where,
        include: WARNING_INCLUDE,
        orderBy: { createdAt: "desc" },
        skip,
        take,
      }),
    ]);

    return ok({ data: rows.map(toWarningRecord), total, page, pageSize });
  });
}

// ---------------------------------------------------------------------------
// POST /api/warnings — issue a manual warning (rating penalty in transaction)
// ---------------------------------------------------------------------------

const createSchema = z.object({
  employeeId: z.string().min(1, "Employee is required"),
  reason: z.string().min(1, "Reason is required").max(500, "Reason must be 500 characters or fewer"),
  absentDates: z.array(zYmd).optional(),
});

export async function POST(req: NextRequest) {
  return routeGuard(async () => {
    const auth = await requirePermission(req, "warnings");
    if (auth.error) return auth.error;

    const { data: body, error: parseError } = await parseWith(req, createSchema);
    if (parseError) return parseError;

    const employee = await db.employee.findUnique({
      where: { id: body.employeeId },
      select: { id: true, fullName: true, employeeCode: true, rating: true, status: true },
    });
    if (!employee) return fail("Employee not found", 404);
    if (employee.status !== "active") return fail("Employee is not active", 400);

    const settings = await getSettings();
    const penalty = settings.warningRatingPenalty;
    const newRating = Math.max(0, round2(employee.rating - penalty));
    const absentDates = body.absentDates ?? null;
    const recipients = await reviewAudience("warnings", auth.user.id);

    const created = await db.$transaction(async (tx) => {
      const warning = await tx.warning.create({
        data: {
          employeeId: employee.id,
          reason: body.reason,
          isAutoGenerated: false,
          absentDates: absentDates ? JSON.stringify(absentDates) : null,
          ratingPenalty: penalty,
          createdByName: auth.user.fullName,
        },
      });
      await tx.employee.update({
        where: { id: employee.id },
        data: { rating: newRating },
      });
      if (recipients.length > 0) {
        await tx.notification.createMany({
          data: recipients.map((recipientId) => ({
            recipientId,
            type: "warning",
            title: "Warning issued",
            message: `${auth.user.fullName} issued a warning to ${employee.fullName} (${employee.employeeCode}).`,
            referenceType: "warning",
            referenceId: warning.id,
          })),
        });
      }
      await tx.auditLog.create({
        data: {
          actorId: auth.user.id,
          actorName: auth.user.fullName,
          action: "warning.create",
          entity: "warning",
          entityId: warning.id,
          before: JSON.stringify({ rating: employee.rating }),
          after: JSON.stringify({
            employeeId: employee.id,
            employeeCode: employee.employeeCode,
            reason: body.reason,
            newRating,
          }),
        },
      });
      return warning;
    });

    return ok({
      ...toWarningRecord({
        ...created,
        employee: { fullName: employee.fullName, employeeCode: employee.employeeCode },
      }),
      newRating,
    });
  });
}
